# Generated by Django 3.2.9 on 2021-12-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_last_name', models.CharField(max_length=50, verbose_name='Фамилия водителя:')),
                ('driver_first_name', models.CharField(max_length=50, verbose_name='Имя водителя:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(max_length=50, verbose_name='Модель автомобиля:')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Марка автомобиля:')),
                ('vehicle_plate_number', models.CharField(max_length=50, verbose_name='Номер автомобиля:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.driver')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
